# general
gpu_id: 2
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: False
save_dataset: False
dataset_save_path: ~
save_dataloaders: False
dataloaders_save_path: ~

# model


# training settings
epochs: 200
train_batch_size: 4096
learner: adam
learning_rate: 0.001
neg_sampling:
  uniform: 1
eval_step: 1
stopping_step: 10
clip_grad_norm: ~
# clip_grad_norm:  {'max_norm': 5, 'norm_type': 2}
weight_decay: 0.0
loss_decimal_place: 4
#threshold:
#  rating:5


# evaluation settings
eval_args:
  split: {'RS':[0.8,0.1,0.1]}  #{'LS':'valid_and_test'} #
  group_by: user
  order: TO
  mode: uni100 # 采样耗时
repeatable: False
metrics: ["MRR","MAP","Recall","Precision","Hit","F1","NDCG"]  #F1
topk: [10]
valid_metric: F1@10
valid_metric_bigger: True
eval_batch_size: 4096
metric_decimal_place: 4